<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >

  <head>
		<base href="http://www.ixion.org.uk/" />
		<title>General stuff</title>
<meta name="generator" content="SilverStripe - http://silverstripe.org" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />

		<link rel="shortcut icon" href="/favicon.ico" />

		<!--[if IE]>
			<style type="text/css">
			 @import url(themes/haze/css/ie.css);
			</style>
		<![endif]-->
		<!--[if IE 6]>
			<style type="text/css">
			 @import url(themes/haze/css/ie6.css);
			</style>
		<![endif]-->
		
	<link rel="stylesheet" type="text/css" href="http://www.ixion.org.uk/themes/haze/css/layout.css?m=1300746972" />
<link rel="stylesheet" type="text/css" href="http://www.ixion.org.uk/themes/haze/css/typography.css?m=1301315463" />
<link rel="stylesheet" type="text/css" href="http://www.ixion.org.uk/themes/haze/css/form.css?m=1197575356" />
<link rel="stylesheet" type="text/css" href="http://www.ixion.org.uk/image_gallery/css/ImageGallery.css?m=1238257202" />
<link rel="stylesheet" type="text/css" href="http://www.ixion.org.uk/image_gallery/gallery_ui/fancybox/css/fancy.css?m=1269282672" />
</head>
<body>
<div id="Container">
	<div id="Header">
<img src="/images/ixmetal.gif" height="70" alt="ixion metal logo"/>
	
	</div>
	<div id="Navigation">
		<ul>
 		  
  		<li><a href="/" title="Go to the Home page" class="link"><span>Home</span></a></li>
   		  
  		<li><a href="/events/" title="Go to the Events page" class="link"><span>Events</span></a></li>
   		  
  		<li><a href="/more-about-ixies/" title="Go to the More about Ixies page" class="link"><span>About</span></a></li>
   		  
  		<li><a href="/ixie-stories/" title="Go to the Ixie Stories page" class="link"><span>Stories</span></a></li>
   		  
  		<li><a href="/riding-tips-and-techniques/" title="Go to the Riding Tips and Techniques page" class="link"><span>Riding Tips</span></a></li>
   		  
  		<li><a href="/gallery/" title="Go to the Gallery page" class="current"><span>Gallery</span></a></li>
   		  
  		<li><a href="/useful-links/" title="Go to the Useful Links page" class="link"><span>Useful Links</span></a></li>
   		  
  		<li><a href="http://ixiemaster.ixion.org.uk/cgi-bin/mailman/listinfo/ixion" title="Go to the Join Us page" class="link"><span>Join Us</span></a></li>
   		  
  		<li><a href="/digest/" title="Go to the Digest page" class="link"><span>Digest</span></a></li>
   	
 </ul>
	</div>
	<div id="LayoutContainer">
		<div id="primaryContent">
<div class="innerpad">
<div class="typography">
	
		<div id="Sidebar" class="typography">
			<div class="sidebarBox">
				<h3>Gallery</h3>
				<ul id="Menu2">
				
					<li class="link"><a class="link" href="/gallery/album/highbury-vaults-2001" title="Highbury Vaults 2001">Highbury Vaults 2001</a></li>
				
				</ul>
				<div class="clear"></div>
			</div>
			<div class="sidebarBottom"></div>
		</div>
	<div id="Content">
	
		<h2>Highbury Vaults 2001</h2>
		<div class="gallery-layout-wrapper">
	
	<ul class="gallery-layout" id="gallery-list">
		
		
			<li>
					<a id="ViewLink-26" rel="fancybox" class="fancybox" title="Four blokes" href="/assets/image-gallery/Gallery/highbury-vaults-2001/_resampled/SetWidth600-Four-blokes.JPG">
	<img src="/assets/image-gallery/Gallery/highbury-vaults-2001/_resampled/croppedimage128128-Four-blokes.JPG" alt="#26"/>
</a>
			</li>
		
			<li>
					<a id="ViewLink-27" rel="fancybox" class="fancybox" title="Four silly blokes" href="/assets/image-gallery/Gallery/highbury-vaults-2001/_resampled/SetWidth600-Four-silly-blokes.JPG">
	<img src="/assets/image-gallery/Gallery/highbury-vaults-2001/_resampled/croppedimage128128-Four-silly-blokes.JPG" alt="#27"/>
</a>
			</li>
		
			<li>
					<a id="ViewLink-28" rel="fancybox" class="fancybox" title="Three limeys and a yank" href="/assets/image-gallery/Gallery/highbury-vaults-2001/_resampled/SetWidth600-Three-Limeys-and-a-Yank.JPG">
	<img src="/assets/image-gallery/Gallery/highbury-vaults-2001/_resampled/croppedimage128128-Three-Limeys-and-a-Yank.JPG" alt="#28"/>
</a>
			</li>
		
		
	</ul>
	
</div>
		<div class="album-nav">
			<ul>
			
			
			</ul>
		</div>
		
	
		</div>
	
</div>
</div>
</div>

	
	
	
	</div>
</div>
<script type="text/javascript" src="http://www.ixion.org.uk/image_gallery/javascript/imagegallery_init.js?m=1251465430"></script><script type="text/javascript" src="http://www.ixion.org.uk/sapphire/thirdparty/jquery/jquery.js?m=1268274554"></script><script type="text/javascript" src="http://www.ixion.org.uk/image_gallery/gallery_ui/fancybox/javascript/jquery.fancybox.js?m=1269282770"></script><script type="text/javascript" src="http://www.ixion.org.uk/image_gallery/gallery_ui/fancybox/javascript/jquery.pngFix.pack.js?m=1251465401"></script><script type="text/javascript" src="http://www.ixion.org.uk/image_gallery/gallery_ui/fancybox/javascript/fancybox_init.js?m=1252375526"></script><script type="text/javascript">//<![CDATA[
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">try{
var pageTracker = _gat._getTracker("UA-22125220-1");
pageTracker._trackPageview();
} catch(err) {}

//]]></script></body>
</html>
